CONFIG_SPI=y                   
CONFIG_INPUT=y                  
CONFIG_ZMK_MOUSE=y          
CONFIG_ZMK_EXT_POWER=y        

CONFIG_PMW3610=y                           
CONFIG_PMW3610_CPI=1600                     
CONFIG_PMW3610_CPI_DIVIDOR=4                
CONFIG_PMW3610_ORIENTATION_270=y           
CONFIG_PMW3610_INVERT_X=y                 

CONFIG_PMW3610_SNIPE_CPI=400                
CONFIG_PMW3610_SNIPE_CPI_DIVIDOR=4          

CONFIG_PMW3610_SCROLL_TICK=24               
CONFIG_PMW3610_POLLING_RATE_125_SW=y      
CONFIG_PMW3610_SMART_ALGORITHM=y

# CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=250  

CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=2000
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=20
CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=5000
CONFIG_PMW3610_REST2_SAMPLE_TIME_MS=50
CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=30000
CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=100    

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

